### ISSUE TITLE
Layout timeout

### ISSUE THREAD

**Issue by srekkas** [xibosignage/xibo-linux#178]
**Describe the bug**
Video restarts every ~10 seconds if widget timeout is not set.

**To Reproduce**
Set default layout with local video widget to player.

**Expected behavior**
Widget must not timeout if not timeout set.

**Logs**
layout XX Expired.

**Screenshots**

**Environment (please complete the following information):**
- Linux Disto: Ubuntu 18.04
- Linux Desktop Environment: Gnome
- How the player was launched: Snap
- Player Version:  1.8-R4 and R4 candidate 40

**Comment by alexharrington** [comment]
That is the intended and expected behaviour. It's not possible to have widgets that never expire. If you don't specify a duration, then the default for that widget is applied, which is 10 seconds in your case.

You need to specify a longer duration on the widget if you want it to be shown for longer.

**Comment by srekkas** [comment]
So why this option is needed, maybe it can show field with 10 seconds and not check mark?

_Set a duration?
Select to provide a specific duration for this Widget_

**Comment by alexharrington** [comment]
It's needed because with a video stream, we can't know how long the file is as they have no fixed end. You must define a length of time that the stream should be shown for.
